---
- name: Apply common config to all node
  hosts: all
  remote_user: pi
  gather_facts: True
  become: true

  vars_files:
    - './vars/users.yaml'

  roles:
    - common
    - users

  tags:
    - common

- name: Apply config to pihole
  hosts: pihole
  remote_user: pi
  become: true

  tasks:
    - name: Set hostname
      hostname:
        name: "pihole{{ groups['pihole'].index(inventory_hostname) + 1 }}"

  tags:
    - pihole

- name: Apply config to unifi-controller
  hosts: unifi-controller
  remote_user: pi
  become: true

  tasks:
    - name: Set hostname
      hostname:
        name: unifi-controller

  roles:
    - unifi

  tags:
    - unifi
