---
- name: Install java sdk
  apt:
    name: oracle-java8-jdk
    state: present

- name: Add ubnt repo key
  become: yes
  become_method: sudo
  apt_key:
    url: https://dl.ubnt.com/unifi/unifi-repo.gpg
    state: present
  notify: 'apt-get update'

- name: Copy unifi apt repo
  copy:
    src: 100-ubnt-unifi.list
    dest: /etc/apt/sources.list.d
    mode: 0644
    owner: root
    group: root
  notify: 'apt-get update'

- name: Add java for unifi
  apt_repository:
    repo: deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main
    state: present
    filename: webupd8team-java
  notify: 'apt-get update'

- name: Install unifi
  become: yes
  become_method: sudo
  apt:
    name: unifi
    state: present

- name: Install java jdk
  become: yes
  become_method: sudo
  apt:
    name: oracle-java8-jdk
    state: present
