---
- name: "Install common packages"
  become: yes
  become_method: sudo
  apt:
    pkg: "{{ packages }}"
    state: present
    update_cache: yes

- name: 'Adjust APT update intervals'
  become: yes
  become_method: sudo
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/10periodic
